const data ={
    products:[
        {
            _id: '1',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
        {
            _id: '2',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
        {
            _id: '3',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
        {
            _id: '4',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
        {
            _id: '5',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
        {
            _id: '6',
            name: 'Peter England Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            decription:'high quality product',
        },
    ],
}

export default data;